version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80

  mysql:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${DB_MYSQL_NAME}
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_PORT=${DB_MYSQL_PORT}
    ports:
      - ${DB_MYSQL_PORT}:${DB_MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
      - PMA_HOST=mysql
    ports:
      - 8080:80
